### ISSUE TITLE
README.rst not included in PyPI

### ISSUE THREAD

**Issue by guacke** [nlesc-nano/AssertionLib#31]
This [README](https://github.com/nlesc-nano/AssertionLib/blob/master/assertionlib/README.rst) is loaded in the [`__init__.py`](https://github.com/nlesc-nano/AssertionLib/blob/master/assertionlib/__init__.py). However, as this README is not included in the [PyPI distribution](https://files.pythonhosted.org/packages/ff/17/08b4207ce11ada5a649c25a123d08c1da75cf9c629b0c0ba86857b82bd23/AssertionLib-3.2.1.tar.gz), this causes errors when trying to import the package:

```bash
failing sanity check for 'AssertionLib' extension: command "python -c "import assertionlib"" failed; output:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/lib/python3.9/site-packages/assertionlib/__init__.py", line 14, in <module>
    __doc__ = load_readme(_README, encoding='utf-8')
  File "/lib/python3.9/site-packages/assertionlib/functions.py", line 467, in load_readme
    with open(readme, **kwargs) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/lib/python3.9/site-packages/assertionlib/README.rst', 
```

**Comment by BvB93** [comment]
Hi @guacke, thanks for the report.
The issue has been fixed as of the recent 3.2.2 release.
